/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'electric-orange':           '#FF5722',
        'on-primary-fixed-variant':  '#862200',
        'outline':                   '#ab8980',
        'primary-fixed-dim':         '#ffb5a0',
        'error':                     '#ffb4ab',
        'on-tertiary-fixed-variant': '#004c6d',
        'surface-container-lowest':  '#180b07',
        'background':                '#1e100c',
        'on-background':             '#fadcd4',
        'surface-dim':               '#1e100c',
        'secondary-fixed':           '#e0e0ff',
        'on-error-container':        '#ffdad6',
        'surface-container':         '#2c1c17',
        'on-tertiary':               '#00344c',
        'secondary':                 '#bdc2ff',
        'tertiary-container':        '#019ad8',
        'status-expired':            '#F44336',
        'surface':                   '#1e100c',
        'inverse-on-surface':        '#3e2c27',
        'primary-container':         '#ff5722',
        'surface-variant':           '#43302b',
        'surface-container-highest': '#43302b',
        'surface-container-high':    '#372621',
        'primary-fixed':             '#ffdbd1',
        'on-secondary':              '#1b247f',
        'on-error':                  '#690005',
        'on-primary-container':      '#541200',
        'on-primary-fixed':          '#3b0900',
        'surface-container-low':     '#271813',
        'inverse-surface':           '#fadcd4',
        'deep-navy':                 '#1A237E',
        'secondary-container':       '#343d96',
        'surface-bright':            '#483530',
        'primary':                   '#ffb5a0',
        'on-tertiary-fixed':         '#001e2e',
        'on-tertiary-container':     '#002d43',
        'tertiary-fixed-dim':        '#86cfff',
        'status-active':             '#4CAF50',
        'on-surface-variant':        '#e4beb4',
        'member-surface':            '#1E1E1E',
        'on-surface':                '#fadcd4',
        'tertiary-fixed':            '#c8e6ff',
        'tertiary':                  '#86cfff',
        'outline-variant':           '#5b4039',
        'inverse-primary':           '#b02f00',
        'on-secondary-container':    '#a8afff',
        'error-container':           '#93000a',
        'status-pending':            '#FFC107',
        'on-secondary-fixed':        '#000767',
        'surface-tint':              '#ffb5a0',
        'secondary-fixed-dim':       '#bdc2ff',
        'member-bg':                 '#121212',
        'on-secondary-fixed-variant':'#343d96',
        'on-primary':                '#5f1500',
      },
      fontFamily: {
        inter:  ['Inter', 'sans-serif'],
        lexend: ['Lexend', 'sans-serif'],
        sans:   ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm':    ['14px', { lineHeight: '1.5',  fontWeight: '400' }],
        'display-lg': ['40px', { lineHeight: '1.2',  fontWeight: '700' }],
        'body-lg':    ['16px', { lineHeight: '1.6',  fontWeight: '400' }],
        'headline-md':['24px', { lineHeight: '1.3',  fontWeight: '600' }],
        'label-bold': ['12px', { lineHeight: '1.0',  letterSpacing: '0.05em', fontWeight: '700' }],
        'stats-num':  ['32px', { lineHeight: '1.0',  fontWeight: '700' }],
      },
      spacing: {
        'touch-target-min':          '44px',
        'gutter':                    '16px',
        'container-margin-mobile':   '16px',
        'container-margin-desktop':  '32px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      animation: {
        'pulse-slow':    'pulse 3s ease-in-out infinite',
        'fade-in':       'fadeIn 0.4s ease-out',
        'slide-up':      'slideUp 0.4s ease-out',
      },
      keyframes: {
        fadeIn:  { from: { opacity: '0' },                    to: { opacity: '1' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
      },
    },
  },
  plugins: [],
}
